#!/usr/bin/env python
import common
import subprocess


def main():
    repo_root = common.find_repo_root()
    config = common.read_config()
    hostname = common.get_hostname(config)
    subprocess.check_call([
        'rsync',
        '-avz',
        '--exclude=node_modules',
        '--exclude=src/expo',
        '.',
        'pi@%s:/home/pi/src/rpi-clock' % hostname,
    ],
    cwd=repo_root)


if __name__ == '__main__':
    main()
