#!/bin/bash

# TODO(mbolin): Read values from config.toml.
cd `git rev-parse --show-toplevel`
rsync -avz \
  --exclude=node_modules \
  --exclude=src/expo \
  . \
  pi@raspberrypi.local:/home/pi/src/rpi-clock
