#!/usr/bin/env python
import common
import json
import os
import subprocess


def main():
    config = common.read_config()
    hostname, port = config.get_webserver_host()

    app_json = {
      "expo": {
        "name": "expo",
        "description": "This project is really great.",
        "slug": "expo",
        "privacy": "public",
        "sdkVersion": "25.0.0",
        "platforms": ["ios", "android"],
        "version": "1.0.0",
        "orientation": "portrait",
        "icon": "./assets/icon.png",
        "splash": {
          "image": "./assets/splash.png",
          "resizeMode": "contain",
          "backgroundColor": "#ffffff"
        },
        "ios": {
          "supportsTablet": True
        },
        "extra": {
            "webserverHostname": hostname,
            "webserverPort": port,
        }
      }
    }

    repo_root = common.find_repo_root()
    app_json_file = os.path.join(repo_root, 'src', 'expo', 'app.json')
    common.mkdirp(os.path.dirname(app_json_file))
    with open(app_json_file, 'w') as f:
        json.dump(app_json, f, indent=2)


if __name__ == '__main__':
    main()
