#!/usr/bin/env python
import common
import os
import subprocess


def main():
    repo_root = common.find_repo_root()

    gen_dir = os.path.join(repo_root, 'gen')
    common.mkdirp(gen_dir)
    grpc_dir = os.path.join(gen_dir, 'grpc')
    common.mkdirp(grpc_dir)

    gen_grpc('src/segment7-service/segment7.proto', repo_root, grpc_dir)
    gen_grpc('src/controller-service/controller.proto', repo_root, grpc_dir)


def gen_grpc(proto_file, repo_root, grpc_dir):
    subprocess.check_call([
        'python',
        '-m',
        'grpc.tools.protoc',
        '-I/usr/local/include',
        '--python_out=%s' % grpc_dir,
        '--grpc_python_out=%s' % grpc_dir,
        '--proto_path',
        os.path.dirname(proto_file),
        proto_file,
    ],
    cwd=repo_root)

if __name__ == '__main__':
    main()
